name: GFG Progress Tracker

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:

jobs:
  update_gfg_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run GFG Scraper
        run: python main.py
